version: '2'

services:
  magic8ball:
    image: stevelasker/magic8ballbatchsample${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
      - "com.microsoft.visualstudio.projectname=Magic8Ball"
